name: Build and Test Spring Boot Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: adopt
        
    - name: Build with Gradle
      run: gradle build
      
    - name: Test with JUnit
      run: gradle test
      
    - name: Generate Jacoco coverage report
      run: gradle jacocoTestReport
      
    - name: Upload coverage data to codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        path: build/reports/jacoco/test/html
